### ISSUE TITLE
Gestion des sélecteurs avec pseudo-classes logiques

### ISSUE THREAD

**Issue by enguerranws** [YannisDelmas/explain-expression#11]
Quelques pseudo-classes (un peu exotiques) ne sont pas prises en charges. 

Liste à compléter :
- :dir()
- :lang()
- :where()

**Comment by YannisDelmas** [comment]
`:dir()` et `:where()` sont des sélecteurs CSS4, ça n'est donc peut-être pas si urgent…
En revanche, il faut corriger le problème de `:lang()`. Je vais regarder ça.

**Comment by YannisDelmas** [comment]
Je viens de corriger le bug avec `:lang()`. Pour les deux autres suggestions, on pourrait ajouter `:is()`, je propose de mettre ça en "enhancement" et d'attendre.

**Comment by YannisDelmas** [comment]
J'ai renommé l'issue: la question est sensiblement la même pour tous les [sélecteurs logiques du CSS4](https://www.w3.org/TR/selectors/#logical-combination).
Pour ce qui concerne `:dir()`, l'analyseur syntaxique fonctionne. Il resterait à l'ajouter aux explications.

**Comment by YannisDelmas** [comment]
Méthode :
- Pour l'analyse syntaxique, utiliser un type 'logical' (voir ident. dans la recommandation) avec des soustypes `not`, `where` etc.
- Pour la spécificité, remplacer le tableau actuel par un tableau contenant des fonctions de calcul, sous forme de chaînes. A l'initialisation: map(eval).

**Comment by YannisDelmas** [comment]
J'ai mis tout ça en œuvre : `:dir()` et sélecteurs logiques de niveau 4.
