### ISSUE TITLE
Des diagrammes pour les sélécteurs CSS?

### ISSUE THREAD

**Issue by YannisDelmas** [YannisDelmas/explain-expression#21]
Exemple: le sélecteur CSS
```CSS
.controle + input, body.test #xyz.abc:hover ~ D
```

pourrait correspondre au diagramme

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgY2xhc3NEZWYgY29tbWVudCBzdHJva2U6bm9uZSxmaWxsOm5vbmU7XG4gIGNsYXNzRGVmIGNpYmxlIHN0cm9rZTojNjY2NkZGLHN0cm9rZS13aWR0aDozcHgsY29sb3I6IzY2NjZGRjtcbiAgY2xhc3NEZWYgY2xhc3NlIHN0cm9rZTojMDA2NjAwLGZpbGw6I0VFRkZFRSxjb2xvcjojMDA2NjAwO1xuICBjbGFzc0RlZiBpZCBzdHJva2U6IzY2MDAwMCxmaWxsOiNGRkVFRUUsY29sb3I6IzY2MDAwMDtcbiAgY2xhc3NEZWYgZWx0IHN0cm9rZTojMDAwMDAwLGZpbGw6I0VFRUVFRTtcbiAgJSUgLmNvbnRyb2xlICsgaW5wdXQsIGJvZHkudGVzdCAjeHl6LmFiYzpob3ZlciB-IERcbiAgc3ViZ3JhcGggY2FzIDJcbiAgICBBe3tib2R5fX06OjplbHRcbiAgICBBIC0tLSBBMShbXCJjbGFzc2UgwqsgdGVzdCDCu1wiXSk6OjpjbGFzc2VcbiAgICBsaW5rU3R5bGUgMCBzdHJva2U6IzAwNjYwMFxuICAgIEJ7eyp9fTo6OmVsdFxuICAgIEEgLS4tPnxjb250aWVudHwgQlxuICAgIEIgLS0tIEIxWy9cImlkIMKrIHh5eiDCu1wiL106OjppZFxuICAgIGxpbmtTdHlsZSAyIHN0cm9rZTojNjYwMDAwXG4gICAgQiAtLS0gQjIoW1wiY2xhc3NlIMKrIGFiYyDCu1wiXSk6OjpjbGFzc2VcbiAgICBsaW5rU3R5bGUgMyBzdHJva2U6IzAwNjYwMFxuICAgIEIyIC0tLSBCMyhbXCJzdXJ2b2zDqVwiXSk6OjpjbGFzc2VcbiAgICBsaW5rU3R5bGUgNCBzdHJva2U6IzAwNjYwMFxuICAgIEEgLS0tIENbXCIuLi5cIl06Ojpjb21tZW50XG4gICAgbGlua1N0eWxlIDUgc3Ryb2tlOm5vbmVcbiAgICBBIC0tLSBEe3tEfX06OjpjaWJsZVxuICAgIGxpbmtTdHlsZSA2IHN0cm9rZTpub25lXG4gIGVuZFxuICBzdWJncmFwaCBcImNhcyAxXCJcbiAgICBFe3sqfX06OjplbHRcbiAgICBFIC0tPiBGe3sqfX06OjplbHRcbiAgICBGIC0tLSBGMShbXCJjbGFzc2UgwqsgY29udHJvbGUgwrtcIl0pOjo6Y2xhc3NlXG4gICAgRSAtLT4gR3t7aW5wdXR9fTo6OmNpYmxlXG4gICAgbGlua1N0eWxlIDggc3Ryb2tlOiMwMDY2MDBcbiAgZW5kXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCIsImZsb3djaGFydCI6eyJjdXJ2ZSI6ImJhc2lzIn19LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgY2xhc3NEZWYgY29tbWVudCBzdHJva2U6bm9uZSxmaWxsOm5vbmU7XG4gIGNsYXNzRGVmIGNpYmxlIHN0cm9rZTojNjY2NkZGLHN0cm9rZS13aWR0aDozcHgsY29sb3I6IzY2NjZGRjtcbiAgY2xhc3NEZWYgY2xhc3NlIHN0cm9rZTojMDA2NjAwLGZpbGw6I0VFRkZFRSxjb2xvcjojMDA2NjAwO1xuICBjbGFzc0RlZiBpZCBzdHJva2U6IzY2MDAwMCxmaWxsOiNGRkVFRUUsY29sb3I6IzY2MDAwMDtcbiAgY2xhc3NEZWYgZWx0IHN0cm9rZTojMDAwMDAwLGZpbGw6I0VFRUVFRTtcbiAgJSUgLmNvbnRyb2xlICsgaW5wdXQsIGJvZHkudGVzdCAjeHl6LmFiYzpob3ZlciB-IERcbiAgc3ViZ3JhcGggY2FzIDJcbiAgICBBe3tib2R5fX06OjplbHRcbiAgICBBIC0tLSBBMShbXCJjbGFzc2UgwqsgdGVzdCDCu1wiXSk6OjpjbGFzc2VcbiAgICBsaW5rU3R5bGUgMCBzdHJva2U6IzAwNjYwMFxuICAgIEJ7eyp9fTo6OmVsdFxuICAgIEEgLS4tPnxjb250aWVudHwgQlxuICAgIEIgLS0tIEIxWy9cImlkIMKrIHh5eiDCu1wiL106OjppZFxuICAgIGxpbmtTdHlsZSAyIHN0cm9rZTojNjYwMDAwXG4gICAgQiAtLS0gQjIoW1wiY2xhc3NlIMKrIGFiYyDCu1wiXSk6OjpjbGFzc2VcbiAgICBsaW5rU3R5bGUgMyBzdHJva2U6IzAwNjYwMFxuICAgIEIyIC0tLSBCMyhbXCJzdXJ2b2zDqVwiXSk6OjpjbGFzc2VcbiAgICBsaW5rU3R5bGUgNCBzdHJva2U6IzAwNjYwMFxuICAgIEEgLS0tIENbXCIuLi5cIl06Ojpjb21tZW50XG4gICAgbGlua1N0eWxlIDUgc3Ryb2tlOm5vbmVcbiAgICBBIC0tLSBEe3tEfX06OjpjaWJsZVxuICAgIGxpbmtTdHlsZSA2IHN0cm9rZTpub25lXG4gIGVuZFxuICBzdWJncmFwaCBcImNhcyAxXCJcbiAgICBFe3sqfX06OjplbHRcbiAgICBFIC0tPiBGe3sqfX06OjplbHRcbiAgICBGIC0tLSBGMShbXCJjbGFzc2UgwqsgY29udHJvbGUgwrtcIl0pOjo6Y2xhc3NlXG4gICAgRSAtLT4gR3t7aW5wdXR9fTo6OmNpYmxlXG4gICAgbGlua1N0eWxlIDggc3Ryb2tlOiMwMDY2MDBcbiAgZW5kXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCIsImZsb3djaGFydCI6eyJjdXJ2ZSI6ImJhc2lzIn19LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

**Comment by enguerranws** [comment]
_Désolé du retard, j'avais bien vu la proposition mais j'ai été happé par (trop) d'autres choses._ 

Alors en fait, la question que je me posais c'est : quel serait le but d'un tel diagramme ? Si c'est à visée pédagogique, pour les étudiants notamment, j'ai peur que ça rende les choses complexes à comprendre (alors que ce qui est déjà en place le fait très bien).

**Comment by YannisDelmas** [comment]
_Mes excuses pour la relance. Je t'avais écrit à partir de ma boîte perso. Je n'étais pas sûr que tu l'avais vu._

OK. Mon idée relève donc plutôt de la manie des programmeurs de toujours vouloir ajouter plus de fonctionnalités, façon obésitiel... Je m'abstiens, donc :smile:

**Comment by enguerranws** [comment]
Alors ce qu'on peut peut être se dire, c'est que ce type d'explications peut correspondre à d'autres types d'apprenants ? (je pense notamment aux devs back-end qui ne comprennent pas comment les sélecteurs CSS fonctionnent) ;)
