### ISSUE TITLE
Utiliser des modules JS

### ISSUE THREAD

**Issue by YannisDelmas** [YannisDelmas/explain-expression#22]
Il faudrait utiliser des [modules JS](https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules) là où c'est utile, plutôt que de simples inclusions de scripts.

**Comment by enguerranws** [comment]
Ah je pensais avoir déjà créé ce ticket. Ce serait effectivement plus confortable (accéder directement aux signatures de fonctions ❤️), plus fiable et plus maintenable.

**Comment by YannisDelmas** [comment]
Bon, ça y est, j'ai fini la rationalisation du code et j'ai transformé les scripts JS en modules. Ça a l'air de fonctionner correctement: j'ai dû pas mal transformer de choses, j'espère n'avoir pas laissé des bugs dans les coins. @enguerranws, tu me diras ce que tu penses des diagrammes pour le CSS #21.
